spring:
  application:
    name: SkillHelper

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SkillDb;encrypt=true;trustServerCertificate=true
    username: sa
    password: Skill_sql_123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    table: schema_history
    out-of-order: false

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
